### ISSUE TITLE
Populate OSCAL metadata

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/bigbang-oscal-component-generator#5]
## Description
Populate the `Root Element`/`UUID`, `Metadata` and `Back Matter` sections when generating the aggregated OSCAL document.

## Technical Details
Referencing [NIST](https://pages.nist.gov/OSCAL/concepts/layer/overview/):
- OSCAL doc needs a document-level UUID that is regenerated at every iteration of the document
- Populated `Metadata` with updated fields as necessary
- Populated `Back Matter` with updated fields as necessary

**Comment by UncleGedd** [comment]
@lucasrod16 !! I forgot this existed 🤣 Great work!

**Comment by lucasrod16** [comment]
> @lucasrod16 !! I forgot this existed 🤣 Great work!

@UncleGedd It has been like 9 months since you opened this issue so that's understandable 😂 I appreciate it
